### ISSUE TITLE
npm install @0.8.4 fails

### ISSUE THREAD

**Issue by GetKraken** [chrisa/node-dtrace-provider#101]
There seems to be install failure on npm with the latest 0.8.4 release:

'$npm_node_execpath' is not recognized as an internal or external command,
operable program or batch file.
npm WARN The package validator is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dtrace-provider@0.8.4 install: `$npm_node_execpath scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dtrace-provider@0.8.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Tried at 0.8.3 and install's fine.

**Comment by melloc** [comment]
@GetKraken What version of npm and node are you using, what operating system are you on, and how do you install npm and node (i.e., which package manager)?

**Comment by melloc** [comment]
@GetKraken I'm guessing you're building on Windows, and the environment variable syntax isn't working there. I've reverted the changes for #92 for now, and published `0.8.5`.

**Comment by GetKraken** [comment]
Thanks. Sorry for the slow response been AFK. Yes Windows with npm@5.0.3 and node@v7.1.0.
