### ISSUE TITLE
Use dtrace to attach to another process, then exit

### ISSUE THREAD

**Issue by ORESoftware** [chrisa/node-dtrace-provider#116]
Support question here -

I am wondering if dtrace can "attach" to another process with pid x...then dtrace will exit, or get some signal, when the other process with pid x dies.

is something like that possible?

at the moment, I can use `tail`/`lsof` commands, but those use polling and that's no bueno. I'd like to potentially use something that doesn't involve polling, if possible.

**Comment by melloc** [comment]
@ORESoftware [`dtrace(1M)`](https://illumos.org/man/1M/dtrace) has a `-p` flag that takes a pid. When the process (or processes if several are specified) exit, then it will exit.

You could also use [proc:::exit](http://dtrace.org/guide/chp-proc.html) and [call `exit()`](http://dtrace.org/guide/chp-actsub.html#chp-actsub-exit) when the `pid` matches.

Also, there's a [DTrace mailing list](http://dtrace.org/blogs/mailing-list/) which is better suited for these kinds of questions, as it has many more subscribers than this repository does.

I hope this helps!
