### ISSUE TITLE
Failed assertion when firing unregistered probe name

### ISSUE THREAD

**Issue by watsoncj** [chrisa/node-dtrace-provider#120]
```
$ node -v
v8.11.2
```
```
$ cat dtrace.js
var dtrace = require('dtrace-provider');
var dtraceProvider = dtrace.createDTraceProvider('taniumjs');

dtraceProvider.addProbe('my-probe', 'char *');
dtraceProvider.enable();

dtraceProvider.fire('other-probe', function () {});
```

```
$ node dtrace.js
Assertion failed: (object->InternalFieldCount() > 0), function Unwrap, file ../../../nan/nan_object_wrap.h, line 33.
Abort trap: 6
```

This causes the VM to exit with code 134 and can be a quite difficult to track down. An appropriate error should be thrown instead.

[relevant line in dtrace-provider](https://github.com/chrisa/node-dtrace-provider/blob/master/src/dtrace_provider.cc#L189)
[relevant line in nodejs/nan](https://github.com/nodejs/nan/blob/8d312c2ae64240e76d8f4d428f73854455305567/nan_object_wrap.h#L33)

Thanks for the awesome project!

**Comment by melloc** [comment]
I'd love to make the behaviour to throw an error with a helpful message here, but it seems that today, depending on the node version being used, the process either crashes on the `Unwrap` or we [return here](https://github.com/chrisa/node-dtrace-provider/blob/06f8a6916bf6cbd929ed824f954a84f645b10d9b/src/dtrace_provider.cc#L191). For example, in v0.10 the following test passes against current master:

```javascript
var test = require('tap').test;
var fmt = require('util').format;
var d = require('../dtrace-provider');


test('firing non-existent probes', function (t) {
    var provider = d.createDTraceProvider("nodeapp");
    provider['typenull'] = null;
    provider['typenan'] = provider;

    function cb(p) {
        return [1, 2, 3, 4];
    }

    function tryName(name) {
        console.log(name);
        provider.fire(name, cb);
        t.pass(fmt('fire("%s", cb) should not raise SIGABRT', name));
    }

    tryName('kaboom');
    tryName('typenull');
    tryName('typenan');

    t.end();
});
```

I'm going to update `fire()` to behave consistently across all node versions (by just doing nothing) and make the backwards-incompatible change to throw in a future release.

I've tested these changes with:

- node v0.10.48, v0.12.16, v4.6.0, v7.5.0, v8.9.4, v10.3.0 on OS X
- node v0.10.47, v0.12.16, v4.8.1 on SmartOS

I've published `dtrace-provider@0.8.7` with the fix.
