### ISSUE TITLE
release tags

### ISSUE THREAD

**Issue by robinfehr** [chrisa/node-dtrace-provider#122]
Hey there,

I had the same issue as described here:
https://github.com/chrisa/node-dtrace-provider/commit/06f8a6916bf6cbd929ed824f954a84f645b10d9b

but I couldn't figure out if it already has been released. Until I saw that on npm there are a few newer releases than on github. 

Would be nice to have the tags up to date.

**Comment by guimard** [comment]
+1

**Comment by melloc** [comment]
Hey @robinfehr ,

Sorry about that. I've added the missing tags.

**Comment by guimard** [comment]
Thanks ! https://salsa.debian.org/js-team/node-dtrace-provider/commit/66eb3eaf
