### ISSUE TITLE
Add "license" and "licenses" to package.json

### ISSUE THREAD

**Issue by garthk** [chrisa/node-dtrace-provider#42]
Specifying your [license] in `package.json` makes it a lot easier for your users to find and comply with [GNU Affero] licenses. 

Also giving `licenses` (an array of objects with `type` and `url` keys) helps  users whose legal departments request both the license name *and the text*. See this example from [async]:

      "licenses": [{
        "type": "MIT",
        "url": "https://github.com/caolan/async/raw/master/LICENSE"
      }]

Though `licenses` isn't specified in the [npm package.json spec][license], it *is* supported by the NPM site, as you'll see if you check [async's NPM page][async]. 

[GNU Affero]: http://www.gnu.org/licenses/agpl-3.0.html
[async]: https://npmjs.org/package/async
[asyncpj]: https://github.com/caolan/async/blob/master/package.json
[license]: https://npmjs.org/doc/json.html#license

Thanks!

**Comment by hpurmann** [comment]
It would be really cool if this module gets a license file + license entry in the `package.json`. @chrisa @davepacheco, what do you think about it?

**Comment by davepacheco** [comment]
This sounds good to me.  (There's already a LICENCE file, but we could add a field to package.json.)

**Comment by patrickpilch** [comment]
Licenses are now officially a part of the `package.json` spec. See [here](https://docs.npmjs.com/files/package.json#license). 
It would make license compliance much easier when generating reports for the suits, using tools like [license-checker](https://github.com/davglass/license-checker) or [npm-license-crawler](https://github.com/mwittig/npm-license-crawler).

**Comment by hpurmann** [comment]
Or [advocate](https://github.com/actano/advocate), which generates the most detailed report of modules you are using.

**Comment by davidbarton** [comment]
+1

Could you please use standard license? It is easier to verify MIT, ISC or any standard one that custom text. Thanks!

**Comment by melloc** [comment]
Resolved in b733a45.
