### ISSUE TITLE
Error building on Amazon AWS

### ISSUE THREAD

**Issue by rodrigoreis22** [chrisa/node-dtrace-provider#47]
I'm getting this error:

1623 info dtrace-provider@0.2.8 Failed to exec install script
1624 error dtrace-provider@0.2.8 install: `node-gyp rebuild`
1624 error Exit status 1
1625 error Failed at the dtrace-provider@0.2.8 install script.
1625 error This is most likely a problem with the dtrace-provider package,
1625 error not with npm itself.
1625 error Tell the author that this fails on your system:
1625 error     node-gyp rebuild
1625 error You can get their info via:
1625 error     npm owner ls dtrace-provider
1625 error There is likely additional logging output above.
1626 error System Linux 3.10.35-43.137.amzn1.x86_64
1627 error command "/opt/elasticbeanstalk/node-install/node-v0.10.26-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v0.10.26-linux-x64/bin/npm" "--production" "rebuild"
1628 error cwd /tmp/deployment/application
1629 error node -v v0.10.26
1630 error npm -v 1.4.4
1631 error code ELIFECYCLE
1632 verbose exit [ 1, true ]

**Comment by davepacheco** [comment]
Closing, as it looks like this was resolved a while ago.
