### ISSUE TITLE
"scripts/install.js" does not work on windows

### ISSUE THREAD

**Issue by Pomax** [chrisa/node-dtrace-provider#55]
not because of the `/`, windows understands those just fine (and has since windows 1.0), but it needs to be told what is supposed to run this install.js script. There's more tools than just node that can run .js files, and not every OS allows files to self-specify which tools should run them. Notably, windows (and there are a lot of windows users that use node/npm), Making the script execution explicit by using `node scripts/install.js` should do the trick (as well as make it immediately obvious to someone looking at the package.json what's supposed to happen)

**Comment by peter-murray** [comment]
I am starting to run into issues with this on my systems and supporting developers.

Can we just have a 0.3.x version that does not blow up under windows released as this will make life a lot easier?

**Comment by tjfontaine** [comment]
published in 0.3.2

**Comment by Pomax** [comment]
\o/
