### ISSUE TITLE
feature request: Add support for process.env.npm_config_node_gyp

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [chrisa/node-dtrace-provider#70]
As we have noticed in https://github.com/jxcore/jxcore/issues/678, the `node-gyp` finding pattern is not sufficient if one would call e.g.:

``` bash
$ jx install dtrace-provider
> dtrace-provider@0.6.0 install ...
> jx scripts/install.js

cannot locate npm install
```

This happens when there is no `node-gyp` and/or `npm` available under `/usr/local/lib/node_modules/`.

Therefore I'd like to propose adding support for `process.env.npm_config_node_gyp` which is a result of implementing `npm install --node-gyp=<path-to-custom-node-gyp>` by npm team: https://github.com/npm/npm/pull/4887 .

Thus `scripts/install.js` of `dtrace-provider` would have this added:

``` js
if (process.env.npm_config_node_gyp && fs.existsSync(process.env.npm_config_node_gyp))
  nodegyp = process.env.npm_config_node_gyp;
```

**Comment by melloc** [comment]
From jxcore/jxcore#678 it sounds like you fixed this by changing it to call `npm-cli.js` instead. After the fix for #95 (which was released in `dtrace-provider@0.8.3`), this library uses the `node-gyp` in the `PATH`, which should also take care of fixing this issue.
